### ISSUE TITLE
Add example data set to test model

### ISSUE THREAD

**Issue by GidonFrischkorn** [GidonFrischkorn/bmm-implement-m3#15]
I would suggest to add one of the data sets from the Oberauer & Lewandowsky (2019) paper. Ideally, one that allows to estimate one of the out-of-the box implementations, but also explore the custom M3 implementations to set up the more complicated models specified in the paper.

This could also be nice to later explore the implementation of the non-exponentiated Luce's choice rule and see if we can reproduce the result that were reported in the paper.

**Comment by chenyu-psy** [comment]
I agree that it would be a good idea to add example data set to test model. However, the data sets from Oberauer & Lewandowsky (2019) might not be ideal. The experimental designs in that paper were complex. We can only use it to test M3custom function.

**Comment by GidonFrischkorn** [comment]
For the simpler models, maybe one of the data sets from the Oberauer (2019) paper in Journal of Cognition (Working Memory Capacity Limits Memory for bindings). There are also quite a few conditions in these experiments, but the task was a simple span task. Maybe one of these data sets and then one from the Oberauer & Lewandowsky Psych. Review paper. Let's think about it.

**Comment by GidonFrischkorn** [comment]
I have now added the data for the first experiment of the Oberauer & Lewandowsky (2019) paper. This data set serves as an example for the `M3custom`.

We need to find at least one data set to use for the `M3cs`. For the `M3ss` I still think data from Oberauer (2019) Journal of cognition should work fine.
