### ISSUE TITLE
How to deal with `log(0)` in M3 models using the non-exponentiated Luce's choice rule

### ISSUE THREAD

**Issue by GidonFrischkorn** [GidonFrischkorn/bmm-implement-m3#26]
In `M3custom` and for special cases also in `M3ss` or `M3cs`models it might be the case that in some conditions one of the response categories has 0 candidates. This leads to the activation for that function being zero. As we have to use a log transform when implementing the non-exponentiated Luce's choice rule, this will lead to an error in STAN.

One option would be to set the number of response candidates to a very small non-zero value, effectively setting the activation for the respective category to virtually zero.

The alternative would be to include index variables that switch certain activation formulas on and off when there are no response candidates in one of the categories. On first glance I am however not sure, if that would generalize to all potential implementations.

Irrespective of the solution we come up with, we will have to find a solution for this problem if we want to have a truly flexible implementation of the model in the bmm package.

**Comment by chenyu-psy** [comment]
I think the easiest solution is to add an extremely small value for every equation as follows: 

1. When we use Luce's choice rule, `muResponse ~ log(actResponse * nResponse + 1e-5)`; 
2. When we use Softmax, `muResponse ~ actResponse + log(nResponse + 1e-5)`.

We also can have an index to represent whether the number of candidate for the response equal to zero or not:
1. When we use Luce's choice rule, `muResponse ~ log(actResponse * nResponse + iZero * 1e-5)`; 
2. When we use Softmax, `muResponse ~ actResponse + log(nResponse + iZero * 1e-5)`.

**Comment by GidonFrischkorn** [comment]
We solved this issue by using the same indexing scheme also implemented for varying set sizes in the `mixture3p` and `IMM` models. Additionally, we internally set `nOpts == 0` for the `softmax` choice rule to a very small, non-zero value. This avoids problems with initial values and starting the sampling.
