### ISSUE TITLE
[feature-request] Allow the parameter link to vary between conditions

### ISSUE THREAD

**Issue by chenyu-psy** [GidonFrischkorn/bmm-implement-m3#38]
The parameter link function provides a very convenient way to translate the parameter to a specific range. However, it also restricts the parameter from being set to a value outside of the range (e.g.,The parameter cannot be 0 when using a log link or logit link). 

In some situations, we want to fix a parameter to a specific value that is outside of the boundary (e.g., 0 or 1 when using logit link) in one condition but still be freely estimated in another condition. It is not quite easy with the current M3custom function.

One idea is to allow the parameter link function to input a list with the condition name as the key. Users can then set a different link (or value) for each condition. We can create an index for each condition and switch the formula between conditions.

**Comment by GidonFrischkorn** [comment]
I see your point. But I also wonder if this would make handling the links to complicated. An alternative that I see is educate users about the option to specify different activation functions dependent on conditions. This should achieve similar results, as you could just drop the parameter that should be fixed to values outside the allowed range and fix it to the required value.

This would maintain the consistency of applying the links to parameters that should be freely estimated and provide an alternative approach to fixing parameters.

I see that this requires slightly more work on the user side, but I think the case you are describing is somewhat specific and in most cases you would do model comparison with one model freely estimating the parameters and another model fixing them to the values like 0 or 1 for all conditions.
