### ISSUE TITLE
Parameter `file_refit` does not work in the bmm function

### ISSUE THREAD

**Issue by chenyu-psy** [GidonFrischkorn/bmm-implement-m3#42]
When I set `file_refit` parameter as `on_change`, I got an error message: invalid 'y' type in 'x || y'. It works when I delete this parameter and use the default setting.

**Comment by GidonFrischkorn** [comment]
This is something that we should add as an issue in the general `bmm` repository. I think this will require some additional coding, similar to the implementation of the `file` argument. I can take care of creating this issue in the `bmm` repository.
